---
# Source: demo-app/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello Kubernetes</title>
    </head>
    <body>
        <h1>Hello, Kubernetes!</h1>
        <p>Hello Staging World!</p>
    </body>
    </html>
---
# Source: demo-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
# Source: demo-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: html
          configMap:
            name: demo-app
