apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/omarfawzi/K8s-ArgoCd-Starter'
        revision: HEAD
        directories:
          - path: "argocd-apps/staging/apps/*"
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: 'https://github.com/omarfawzi/K8s-ArgoCd-Starter'
        targetRevision: HEAD
        path: "argocd-apps/staging/apps/{{path.basename}}"
      destination:
        server: 'https://kubernetes.default.svc'
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
