apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello Kubernetes</title>
    </head>
    <body>
        <h1>Hello, Kubernetes!</h1>
        <p>{{ .Values.message }}</p>
    </body>
    </html>