name: Test Helm Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-on-kind:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Kind cluster
      - name: Set up Kind
        uses: helm/kind-action@v1
        with:
          version: "v0.20.0" # Kind version

      # Step 3: Install Helm
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: "v3.12.0" # Helm version

      # Step 4: Install Kubernetes manifests using Helm
      - name: Install Helm Chart
        run: |
          helm repo add stable https://charts.helm.sh/stable
          helm install demo-app ./kube/demo/ -f kube/demo/values-staging.yaml

      # Step 5: Verify Deployment
      - name: Wait for Pods to be ready
        run: |
          kubectl wait --for=condition=ready pod --all --timeout=120s

      - name: Test Application
        run: |
          # Replace with your actual tests
          kubectl get pods
          # kubectl exec -it $(kubectl get pods -l app=demo-app -o jsonpath="{.items[0].metadata.name}") -- curl -f http://localhost:8080/health

      # Step 6: Gather logs (Optional)
      - name: Application Logs
        run: |
          kubectl logs -l app=demo-app > app-logs.txt
          cat app-logs.txt
